### ISSUE TITLE
Is it normal for testing to take ten times longer than training? 

### ISSUE THREAD

**Issue by XiudingCai** [liaoyuhua/GPT-TS#1]
Is it normal for testing to take ten times longer than training? For example:
100%|██████████| 511/511 [04:06<00:00, 2.07it/s]
 13% | ▎ | 22/175 [05:43<40:00, 15.69s/it]

**Comment by 1iaoyuhua** [comment]
The inference stage is a direct autoregressive process, thus it takes longer time. This will be optimized soon.

**Comment by liaoyuhua** [comment]
The inference stage is a direct autoregressive process, thus it takes longer time. This will be optimized soon.
