### ISSUE TITLE
请问哪里使用了patching？

### ISSUE THREAD

**Issue by lzmax888** [liaoyuhua/GPT-TS#2]
论文里面说他使用了patchtst的patching，但是我在那个代码里面没有看到。不知道在哪里？

谢谢

**Comment by liaoyuhua** [comment]
这版没有使用patching，下一版会加上patching、amp和优化推理方法。预计这周更新

**Comment by hu-four** [comment]
非常感谢大佬的代码，给予了我很多的帮助！有一个问题想要问一下：目前代码里实现的任务是单序列对单序列的预测，不知道您复现的结果大概到什么程度？在ETTh1这种公共的数据集上？

**Comment by liaoyuhua** [comment]
> 非常感谢大佬的代码，给予了我很多的帮助！有一个问题想要问一下：目前代码里实现的任务是单序列对单序列的预测，不知道您复现的结果大概到什么程度？在ETTh1这种公共的数据集上？

我没有调参，跑了下单变量etth1，接近informer。

**Comment by liaoyuhua** [comment]
> 论文里面说他使用了patchtst的patching，但是我在那个代码里面没有看到。不知道在哪里？
> 
> 谢谢

已经加上了 参考：https://github.com/liaoyuhua/GPT-TS/blob/931897195cf960aa3ec1aaf0b56716fb08095869/src/model.py#L277C1-L277C9

**Comment by liaoyuhua** [comment]
> 非常感谢大佬的代码，给予了我很多的帮助！有一个问题想要问一下：目前代码里实现的任务是单序列对单序列的预测，不知道您复现的结果大概到什么程度？在ETTh1这种公共的数据集上？

我没有调参，跑了下单变量etth1，比informer好一些。

**Comment by Icecens** [comment]
> 非常感谢大佬的代码，给予了我很多的帮助！有一个问题想要问一下：目前代码里实现的任务是单序列对单序列的预测，不知道您复现的结果大概到什么程度？在ETTh1这种公共的数据集上？

大佬你的结果大概是多少，我的loss甚至到了4.多
