### ISSUE TITLE
Time series classification

### ISSUE THREAD

**Issue by zbjsppp** [liaoyuhua/GPT-TS#3]
您好，请问这个预训练的GPT2模型如何应用到时间序列的分类当中，或者说需要改动模型里面的哪些东西？

**Comment by liaoyuhua** [comment]
可以修改下head：https://github.com/liaoyuhua/GPT-TS/blob/cb901bb92015c68666d9d95c80a49374c70a2fab/src/model.py#L136
核心代码应该是nn.Linear(self.n_embd * self.patch_num, self.num_class)。

**Comment by zbjsppp** [comment]
好的，感谢您的回复！

**Comment by liaoyuhua** [comment]
> 好的，感谢您的回复！

没事
