### ISSUE TITLE
data explosion

### ISSUE THREAD

**Issue by lien99** [liaoyuhua/GPT-TS#6]
在我用自己的数据集做实验的时候发现异常，训练过程中loss会变成nan
我自己的数据集格式如下：

          | date | weather1-ws | weather1-wd | weather2-ws | weather2-wd | windspeed
  2022/5/17 0:00 | 9.3260 | 270.630005 | 7.1254 | 280.970001 | 6.140714
  2022/5/17 1:00 | 8.8101 | 278.660034 | 7.2324 | 282.170013 | 6.735000
  2022/5/17 2:00 | 7.9184 | 287.309998 | 7.5426 | 277.500000 | 5.740714
  2022/5/17 3:00 | 6.6335 | 276.929993 | 6.8170 | 270.130005 | 6.115000
  2022/5/17 4:00 | 7.2535 | 256.570007 | 6.5380 | 262.769989 | 6.461429
  2022/5/17 5:00 | 7.7177 | 263.450012 | 8.3436 | 263.529999 | 5.206429
  2022/5/17 6:00 | 7.1835 | 268.150024 | 8.3883 | 272.790008 | 5.238572
  2022/5/17 7:00 | 7.2290 | 276.119995 | 7.7963 | 270.760010 | 6.201428
  2022/5/17 8:00 | 6.9198 | 285.469971 | 7.9846 | 273.299988 | 5.705714
  2022/5/17 9:00 | 4.5628 | 283.719971 | 8.2281 | 269.339996 | 4.560000
  2022/5/17 10:00 | 4.1537 | 270.390015 | 7.4988 | 269.160004 | 4.640000

`        # encoder
        h = self.encoder(x)  # B, N, E, P
        out = self.head(h)  # B, N, Y

        # denorm
        if self.revin:
            out = out.permute(0, 2, 1)  # B, Y, N
            out = self.revin_layer(out, "denorm")  # B, Y, N
            out = out.permute(0, 2, 1)  # B, N, Y`

经过debug发现out = self.head(h)这一步之后，out中的数据会变得非常大，通常是三位数四位数。这种情况下再进行denorm是不是不太合理？我认为也可能是该原因导致在后续的loss计算中loss为nan。
还希望作者能抽空解答我的问题，不胜感激

**Comment by liaoyuhua** [comment]
> 在我用自己的数据集做实验的时候发现异常，训练过程中loss会变成nan 我自己的数据集格式如下：
> 
>   | date | weather1-ws | weather1-wd | weather2-ws | weather2-wd | windspeed 2022/5/17 0:00 | 9.3260 | 270.630005 | 7.1254 | 280.970001 | 6.140714 2022/5/17 1:00 | 8.8101 | 278.660034 | 7.2324 | 282.170013 | 6.735000 2022/5/17 2:00 | 7.9184 | 287.309998 | 7.5426 | 277.500000 | 5.740714 2022/5/17 3:00 | 6.6335 | 276.929993 | 6.8170 | 270.130005 | 6.115000 2022/5/17 4:00 | 7.2535 | 256.570007 | 6.5380 | 262.769989 | 6.461429 2022/5/17 5:00 | 7.7177 | 263.450012 | 8.3436 | 263.529999 | 5.206429 2022/5/17 6:00 | 7.1835 | 268.150024 | 8.3883 | 272.790008 | 5.238572 2022/5/17 7:00 | 7.2290 | 276.119995 | 7.7963 | 270.760010 | 6.201428 2022/5/17 8:00 | 6.9198 | 285.469971 | 7.9846 | 273.299988 | 5.705714 2022/5/17 9:00 | 4.5628 | 283.719971 | 8.2281 | 269.339996 | 4.560000 2022/5/17 10:00 | 4.1537 | 270.390015 | 7.4988 | 269.160004 | 4.640000
> 
> ` # encoder h = self.encoder(x) # B, N, E, P out = self.head(h) # B, N, Y
> 
> ```
>     # denorm
>     if self.revin:
>         out = out.permute(0, 2, 1)  # B, Y, N
>         out = self.revin_layer(out, "denorm")  # B, Y, N
>         out = out.permute(0, 2, 1)  # B, N, Y`
> ```
> 
> 经过debug发现out = self.head(h)这一步之后，out中的数据会变得非常大，通常是三位数四位数。这种情况下再进行denorm是不是不太合理？我认为也可能是该原因导致在后续的loss计算中loss为nan。 还希望作者能抽空解答我的问题，不胜感激

设置了use_amp=True？

**Comment by lien99** [comment]
> > 在我用自己的数据集做实验的时候发现异常，训练过程中loss会变成nan 我自己的数据集格式如下：
> >   | date | weather1-ws | weather1-wd | weather2-ws | weather2-wd | windspeed 2022/5/17 0:00 | 9.3260 | 270.630005 | 7.1254 | 280.970001 | 6.140714 2022/5/17 1:00 | 8.8101 | 278.660034 | 7.2324 | 282.170013 | 6.735000 2022/5/17 2:00 | 7.9184 | 287.309998 | 7.5426 | 277.500000 | 5.740714 2022/5/17 3:00 | 6.6335 | 276.929993 | 6.8170 | 270.130005 | 6.115000 2022/5/17 4:00 | 7.2535 | 256.570007 | 6.5380 | 262.769989 | 6.461429 2022/5/17 5:00 | 7.7177 | 263.450012 | 8.3436 | 263.529999 | 5.206429 2022/5/17 6:00 | 7.1835 | 268.150024 | 8.3883 | 272.790008 | 5.238572 2022/5/17 7:00 | 7.2290 | 276.119995 | 7.7963 | 270.760010 | 6.201428 2022/5/17 8:00 | 6.9198 | 285.469971 | 7.9846 | 273.299988 | 5.705714 2022/5/17 9:00 | 4.5628 | 283.719971 | 8.2281 | 269.339996 | 4.560000 2022/5/17 10:00 | 4.1537 | 270.390015 | 7.4988 | 269.160004 | 4.640000
> > ` # encoder h = self.encoder(x) # B, N, E, P out = self.head(h) # B, N, Y
> > ```
> >     # denorm
> >     if self.revin:
> >         out = out.permute(0, 2, 1)  # B, Y, N
> >         out = self.revin_layer(out, "denorm")  # B, Y, N
> >         out = out.permute(0, 2, 1)  # B, N, Y`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 经过debug发现out = self.head(h)这一步之后，out中的数据会变得非常大，通常是三位数四位数。这种情况下再进行denorm是不是不太合理？我认为也可能是该原因导致在后续的loss计算中loss为nan。 还希望作者能抽空解答我的问题，不胜感激
> 
> 设置了use_amp=True？

是的，使用了你的默认设置，但是根据我的任务需要我设置了features="MS"

**Comment by liaoyuhua** [comment]
> > > 在我用自己的数据集做实验的时候发现异常，训练过程中loss会变成nan 我自己的数据集格式如下：
> > >   | date | weather1-ws | weather1-wd | weather2-ws | weather2-wd | windspeed 2022/5/17 0:00 | 9.3260 | 270.630005 | 7.1254 | 280.970001 | 6.140714 2022/5/17 1:00 | 8.8101 | 278.660034 | 7.2324 | 282.170013 | 6.735000 2022/5/17 2:00 | 7.9184 | 287.309998 | 7.5426 | 277.500000 | 5.740714 2022/5/17 3:00 | 6.6335 | 276.929993 | 6.8170 | 270.130005 | 6.115000 2022/5/17 4:00 | 7.2535 | 256.570007 | 6.5380 | 262.769989 | 6.461429 2022/5/17 5:00 | 7.7177 | 263.450012 | 8.3436 | 263.529999 | 5.206429 2022/5/17 6:00 | 7.1835 | 268.150024 | 8.3883 | 272.790008 | 5.238572 2022/5/17 7:00 | 7.2290 | 276.119995 | 7.7963 | 270.760010 | 6.201428 2022/5/17 8:00 | 6.9198 | 285.469971 | 7.9846 | 273.299988 | 5.705714 2022/5/17 9:00 | 4.5628 | 283.719971 | 8.2281 | 269.339996 | 4.560000 2022/5/17 10:00 | 4.1537 | 270.390015 | 7.4988 | 269.160004 | 4.640000
> > > ` # encoder h = self.encoder(x) # B, N, E, P out = self.head(h) # B, N, Y
> > > ```
> > >     # denorm
> > >     if self.revin:
> > >         out = out.permute(0, 2, 1)  # B, Y, N
> > >         out = self.revin_layer(out, "denorm")  # B, Y, N
> > >         out = out.permute(0, 2, 1)  # B, N, Y`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 经过debug发现out = self.head(h)这一步之后，out中的数据会变得非常大，通常是三位数四位数。这种情况下再进行denorm是不是不太合理？我认为也可能是该原因导致在后续的loss计算中loss为nan。 还希望作者能抽空解答我的问题，不胜感激
> > 
> > 
> > 设置了use_amp=True？
> 
> 是的，使用了你的默认设置，但是根据我的任务需要我设置了features="MS"

你把use_amp设为False试试，这里混合精度有点问题，后面有空修一下。

**Comment by lien99** [comment]
> > > > 在我用自己的数据集做实验的时候发现异常，训练过程中loss会变成nan 我自己的数据集格式如下：
> > > >   | date | weather1-ws | weather1-wd | weather2-ws | weather2-wd | windspeed 2022/5/17 0:00 | 9.3260 | 270.630005 | 7.1254 | 280.970001 | 6.140714 2022/5/17 1:00 | 8.8101 | 278.660034 | 7.2324 | 282.170013 | 6.735000 2022/5/17 2:00 | 7.9184 | 287.309998 | 7.5426 | 277.500000 | 5.740714 2022/5/17 3:00 | 6.6335 | 276.929993 | 6.8170 | 270.130005 | 6.115000 2022/5/17 4:00 | 7.2535 | 256.570007 | 6.5380 | 262.769989 | 6.461429 2022/5/17 5:00 | 7.7177 | 263.450012 | 8.3436 | 263.529999 | 5.206429 2022/5/17 6:00 | 7.1835 | 268.150024 | 8.3883 | 272.790008 | 5.238572 2022/5/17 7:00 | 7.2290 | 276.119995 | 7.7963 | 270.760010 | 6.201428 2022/5/17 8:00 | 6.9198 | 285.469971 | 7.9846 | 273.299988 | 5.705714 2022/5/17 9:00 | 4.5628 | 283.719971 | 8.2281 | 269.339996 | 4.560000 2022/5/17 10:00 | 4.1537 | 270.390015 | 7.4988 | 269.160004 | 4.640000
> > > > ` # encoder h = self.encoder(x) # B, N, E, P out = self.head(h) # B, N, Y
> > > > ```
> > > >     # denorm
> > > >     if self.revin:
> > > >         out = out.permute(0, 2, 1)  # B, Y, N
> > > >         out = self.revin_layer(out, "denorm")  # B, Y, N
> > > >         out = out.permute(0, 2, 1)  # B, N, Y`
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 经过debug发现out = self.head(h)这一步之后，out中的数据会变得非常大，通常是三位数四位数。这种情况下再进行denorm是不是不太合理？我认为也可能是该原因导致在后续的loss计算中loss为nan。 还希望作者能抽空解答我的问题，不胜感激
> > > 
> > > 
> > > 设置了use_amp=True？
> > 
> > 
> > 是的，使用了你的默认设置，但是根据我的任务需要我设置了features="MS"
> 
> 你把use_amp设为False试试，这里混合精度有点问题，后面有空修一下。

谢谢，这样做的确好了很多，但是loss还是相对比较高的，训练过程中最低的mse loss还是有2.1左右。可能还需要再调吧。我还有个疑问，你的模型为什么不把date数据也用上呢，时间也算比较有用特征吧

**Comment by liaoyuhua** [comment]
> > > > > 在我用自己的数据集做实验的时候发现异常，训练过程中loss会变成nan 我自己的数据集格式如下：
> > > > >   | date | weather1-ws | weather1-wd | weather2-ws | weather2-wd | windspeed 2022/5/17 0:00 | 9.3260 | 270.630005 | 7.1254 | 280.970001 | 6.140714 2022/5/17 1:00 | 8.8101 | 278.660034 | 7.2324 | 282.170013 | 6.735000 2022/5/17 2:00 | 7.9184 | 287.309998 | 7.5426 | 277.500000 | 5.740714 2022/5/17 3:00 | 6.6335 | 276.929993 | 6.8170 | 270.130005 | 6.115000 2022/5/17 4:00 | 7.2535 | 256.570007 | 6.5380 | 262.769989 | 6.461429 2022/5/17 5:00 | 7.7177 | 263.450012 | 8.3436 | 263.529999 | 5.206429 2022/5/17 6:00 | 7.1835 | 268.150024 | 8.3883 | 272.790008 | 5.238572 2022/5/17 7:00 | 7.2290 | 276.119995 | 7.7963 | 270.760010 | 6.201428 2022/5/17 8:00 | 6.9198 | 285.469971 | 7.9846 | 273.299988 | 5.705714 2022/5/17 9:00 | 4.5628 | 283.719971 | 8.2281 | 269.339996 | 4.560000 2022/5/17 10:00 | 4.1537 | 270.390015 | 7.4988 | 269.160004 | 4.640000
> > > > > ` # encoder h = self.encoder(x) # B, N, E, P out = self.head(h) # B, N, Y
> > > > > ```
> > > > >     # denorm
> > > > >     if self.revin:
> > > > >         out = out.permute(0, 2, 1)  # B, Y, N
> > > > >         out = self.revin_layer(out, "denorm")  # B, Y, N
> > > > >         out = out.permute(0, 2, 1)  # B, N, Y`
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 经过debug发现out = self.head(h)这一步之后，out中的数据会变得非常大，通常是三位数四位数。这种情况下再进行denorm是不是不太合理？我认为也可能是该原因导致在后续的loss计算中loss为nan。 还希望作者能抽空解答我的问题，不胜感激
> > > > 
> > > > 
> > > > 设置了use_amp=True？
> > > 
> > > 
> > > 是的，使用了你的默认设置，但是根据我的任务需要我设置了features="MS"
> > 
> > 
> > 你把use_amp设为False试试，这里混合精度有点问题，后面有空修一下。
> 
> 谢谢，这样做的确好了很多，但是loss还是相对比较高的，训练过程中最低的mse loss还是有2.1左右。可能还需要再调吧。我还有个疑问，你的模型为什么不把date数据也用上呢，时间也算比较有用特征吧

这个在第一版的时候用了，但是version 0.2.0的时候删掉了，主要还是和论文对齐。本身这个项目的初衷就是为了复现论文。可以关注下https://github.com/liaoyuhua/largets 这个项目，后续会做一些更贴近实际生产的内容。
